// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYSAJXUpdhEnPgdnzkmBTPbEKdMoTjq6Q',
    appId: '1:317197222230:web:eb732ac8d00344837716f7',
    messagingSenderId: '317197222230',
    projectId: 'flutter-project-1f0a8',
    authDomain: 'flutter-project-1f0a8.firebaseapp.com',
    storageBucket: 'flutter-project-1f0a8.firebasestorage.app',
    measurementId: 'G-4BPD9S5GMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXq9WF061-bbo3wR0auWW5o2h1YaPDv8',
    appId: '1:317197222230:android:3839930b9e2495bd7716f7',
    messagingSenderId: '317197222230',
    projectId: 'flutter-project-1f0a8',
    storageBucket: 'flutter-project-1f0a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkFhWPbdP2BfI3E50q1WMNlB1nID8Uzbg',
    appId: '1:317197222230:ios:1dcc2f927e55ee397716f7',
    messagingSenderId: '317197222230',
    projectId: 'flutter-project-1f0a8',
    storageBucket: 'flutter-project-1f0a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkFhWPbdP2BfI3E50q1WMNlB1nID8Uzbg',
    appId: '1:317197222230:ios:1dcc2f927e55ee397716f7',
    messagingSenderId: '317197222230',
    projectId: 'flutter-project-1f0a8',
    storageBucket: 'flutter-project-1f0a8.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYSAJXUpdhEnPgdnzkmBTPbEKdMoTjq6Q',
    appId: '1:317197222230:web:52dc8b79009d07b87716f7',
    messagingSenderId: '317197222230',
    projectId: 'flutter-project-1f0a8',
    authDomain: 'flutter-project-1f0a8.firebaseapp.com',
    storageBucket: 'flutter-project-1f0a8.firebasestorage.app',
    measurementId: 'G-TXWSTHP66Q',
  );
}
